### PR TITLE
Change NULL to nullptr.

### PR DESCRIPTION
**Pull request by madmaxoft**
Ref.: cuberite/cuberite#4215

### CODE REVIEW

**Comment by QianNangong** [comment]
Not only `NULL`s, some `0`s also break the build progress.

**Comment by madmaxoft** [comment]
Could you give me an example? I don't have access to AppleClang.

I'll fix those in a separate PR, I think this one is pretty clean so it should be no problem to merge.

**Comment by QianNangong** [comment]
I'm pulling source codes from GitHub.
You know, In China there are some limitations visiting GitHub.

**Comment by QianNangong** [comment]
```
[ 50%] Building CXX object src/Bindings/CMakeFiles/Bindings.dir/Bindings.cpp.o
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:338:68: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  Vector3<int>* self = (Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                   ^
                                                                   nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:351:68: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  Vector3<int>* self = (Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                   ^
                                                                   nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:368:68: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  Vector3<int>* self = (Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                   ^
                                                                   nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:381:68: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  Vector3<int>* self = (Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                   ^
                                                                   nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:398:68: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  Vector3<int>* self = (Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                   ^
                                                                   nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:411:68: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  Vector3<int>* self = (Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                   ^
                                                                   nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:553:86: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<float>* a_Rhs = ((const Vector3<float>*)  tolua_tousertype(tolua_S,2,0));
                                                                                     ^
                                                                                     nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:578:86: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<float>* a_Rhs = ((const Vector3<float>*)  tolua_tousertype(tolua_S,2,0));
                                                                                     ^
                                                                                     nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:604:88: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<double>* a_Rhs = ((const Vector3<double>*)  tolua_tousertype(tolua_S,2,0));
                                                                                       ^
                                                                                       nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:629:88: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<double>* a_Rhs = ((const Vector3<double>*)  tolua_tousertype(tolua_S,2,0));
                                                                                       ^
                                                                                       nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:655:82: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<int>* a_Rhs = ((const Vector3<int>*)  tolua_tousertype(tolua_S,2,0));
                                                                                 ^
                                                                                 nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:680:82: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<int>* a_Rhs = ((const Vector3<int>*)  tolua_tousertype(tolua_S,2,0));
                                                                                 ^
                                                                                 nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:710:68: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  Vector3<int>* self = (Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                   ^
                                                                   nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:744:68: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  Vector3<int>* self = (Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                   ^
                                                                   nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:775:80: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<int>* self = (const Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                               ^
                                                                               nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:817:80: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<int>* self = (const Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                               ^
                                                                               nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:849:80: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<int>* self = (const Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                               ^
                                                                               nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:881:80: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<int>* self = (const Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                               ^
                                                                               nullptr
/Users/alpine/cuberite/src/Bindings/Bindings.cpp:914:80: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  const Vector3<int>* self = (const Vector3<int>*)  tolua_tousertype(tolua_S,1,0);
                                                                               ^
                                                                               nullptr
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/Bindings/CMakeFiles/Bindings.dir/Bindings.cpp.o] Error 1
make[1]: *** [src/Bindings/CMakeFiles/Bindings.dir/all] Error 2
make: *** [all] Error 2
```
I've modified `package.lua` and replace `output(' '..i..'* self = ('..i..'*) tolua_tousertype(tolua_S,1,0);')` with `output(' '..i..'* self = ('..i..'*) tolua_tousertype(tolua_S,1,nullptr);')` but it doesn't work.
I can't find another place where `tolua_tousertype` presented.

**Pull request merged**
